# Generated by Django 4.0.3 on 2022-04-14 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0003_appointment_time_alter_appointment_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('date', 'time')},
        ),
    ]
