# Generated by Django 4.0.3 on 2022-05-08 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0005_alter_appointment_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='description',
        ),
    ]
